### ISSUE TITLE
Need a pub func to return current offset

### ISSUE THREAD

**Issue by ydajwz123** [quietvoid/bitvec_helpers#1]
This issue is only a suggestion.
When I use hevc_parser, the current bit offeset is sometimes needed in order to know the global offset in the bitstream. Althogh, I can get it by `len - reader.available()`. Would it be better to add a pub function to return offset immediately?
THANKS for your marvellous work.

**Comment by quietvoid** [comment]
See `BitVecReader::position()`, will push to crates.io.
